-- MySQL Script generated by MySQL Workbench
-- 10/07/15 17:09:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fablab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fablab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fablab` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fablab` ;

-- -----------------------------------------------------
-- Table `fablab`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(512) NOT NULL,
  `forename` VARCHAR(512) NOT NULL,
  `surname` VARCHAR(512) NOT NULL,
  `address_street` VARCHAR(512) NOT NULL,
  `address_postal_code` VARCHAR(512) NOT NULL,
  `address_country` VARCHAR(512) NOT NULL,
  `phone_number` VARCHAR(30) NOT NULL,
  `student_id` VARCHAR(20) NULL,
  `password_hash` VARCHAR(512) NOT NULL,
  `password_salt` VARCHAR(512) NOT NULL,
  `level` INT NOT NULL,
  `quota` DECIMAL NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fablab`.`Machinegroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Machinegroups` (
  `machinegroup_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NULL,
  `Machinegroupscol` VARCHAR(45) NULL,
  PRIMARY KEY (`machinegroup_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fablab`.`Machines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Machines` (
  `machine_id` INT NOT NULL AUTO_INCREMENT,
  `Machinegroups_machinegroup_id` INT NOT NULL,
  `manufacturer` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `needs_supervision` TINYINT(1) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`machine_id`, `Machinegroups_machinegroup_id`),
  INDEX `fk_Machines_Machinegroups_idx` (`Machinegroups_machinegroup_id` ASC),
  CONSTRAINT `fk_Machines_Machinegroups`
    FOREIGN KEY (`Machinegroups_machinegroup_id`)
    REFERENCES `fablab`.`Machinegroups` (`machinegroup_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fablab`.`Userlevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Userlevels` (
  `Users_user_id` INT NOT NULL,
  `Machines_machine_id` INT NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`Users_user_id`, `Machines_machine_id`),
  INDEX `fk_Userlevels_Users1_idx` (`Users_user_id` ASC),
  INDEX `fk_Userlevels_Machines1_idx` (`Machines_machine_id` ASC),
  CONSTRAINT `fk_Userlevels_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `fablab`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Userlevels_Machines1`
    FOREIGN KEY (`Machines_machine_id`)
    REFERENCES `fablab`.`Machines` (`machine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fablab`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Reservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `Machines_machine_id` INT NOT NULL,
  `Users_user_id` INT NOT NULL,
  `start_time` INT NOT NULL,
  `end_time` INT NOT NULL,
  `qrcode` VARCHAR(256) NOT NULL,
  `passcode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`reservation_id`, `Machines_machine_id`, `Users_user_id`),
  INDEX `fk_Reservations_Machines1_idx` (`Machines_machine_id` ASC),
  INDEX `fk_Reservations_Users1_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_Reservations_Machines1`
    FOREIGN KEY (`Machines_machine_id`)
    REFERENCES `fablab`.`Machines` (`machine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `fablab`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fablab`.`Supervisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Supervisions` (
  `supervision_id` INT NOT NULL AUTO_INCREMENT,
  `Users_user_id` INT NOT NULL,
  `start_time` VARCHAR(512) NOT NULL,
  `end_time` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`supervision_id`, `Users_user_id`),
  CONSTRAINT `fk_supervisions_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `fablab`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fablab`.`Settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fablab`.`Settings` (
  `setting_key` VARCHAR(20) NOT NULL,
  `setting_value` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`setting_key`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
